/**
* @author BuiChiThong
* @warn Vui lòng không sửa credits tôn trọng người viết cảm ơn !
*/
module.exports.config = {
  name: "rose",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "BuiChiThong",
  description: "Random Ảnh Rosé",
  commandCategory: "Hình Ảnh",
  usages: "rose",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
};

module.exports.run = async({api,event,args,client,Users,Threads,__GLOBAL,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
"https://i.imgur.com/FnB3Ppc.jpg",
"https://i.imgur.com/OOMeMDn.jpg",
"https://i.imgur.com/ZaM6wms.jpg",
"https://i.imgur.com/PQokCMq.jpg",
"https://i.imgur.com/BuL6BDy.jpg",
"https://i.imgur.com/Fcxy36U.jpg",
"https://i.imgur.com/e184Byc.jpg",
"https://i.imgur.com/nv5GuIN.jpg",
"https://i.imgur.com/CjdnkAt.jpg",
"https://i.imgur.com/HRbszXH.jpg",
"https://i.imgur.com/5jFxO1R.jpg",
"https://i.imgur.com/b5SUNGb.jpg",
"https://i.imgur.com/SjltgNA.jpg",
"https://i.imgur.com/KRYITAb.jpg",
"https://i.imgur.com/40heKbH.jpg",
"https://i.imgur.com/11gVbWd.jpg",
"https://i.imgur.com/E3o3fn9.jpg",
"https://i.imgur.com/ydn5iUU.png",
"https://i.imgur.com/LsXzqcf.jpg",
"https://i.imgur.com/6LMxPtm.jpg",
"https://i.imgur.com/h8Z1T6d.jpg",
"https://i.imgur.com/5vErMmw.jpg",
"https://i.imgur.com/yUOdxwx.jpg",
"https://i.imgur.com/6LMxPtm.jpg",
"https://i.imgur.com/h8Z1T6d.jpg",
"https://i.imgur.com/5vErMmw.jpg",
"https://i.imgur.com/yUOdxwx.jpg",
"https://i.imgur.com/85VNmNC.jpg",
"https://i.imgur.com/Ovr3kuH.jpg",
"https://i.imgur.com/IT2IGqq.jpg",
"https://i.imgur.com/Qh3aJ56.jpg",
"https://i.imgur.com/8NSPh7Z.jpg",
"https://i.imgur.com/Z4bcOz4.jpg",
"https://i.imgur.com/rqqGATb.jpg",
"https://i.imgur.com/5auN1hy.jpg",
"https://i.imgur.com/iVD4SeA.jpg",
"https://i.imgur.com/eXBkWCk.jpg",
"https://i.imgur.com/gvznfeX.jpg",
"https://i.imgur.com/FvbysJI.jpg",
"https://i.imgur.com/2FqbrEF.jpg",
"https://i.imgur.com/H5Dly6M.jpg",
"https://i.imgur.com/VQBwiyF.jpg",
"https://i.imgur.com/ZdLO08z.jpg",
"https://i.imgur.com/nzYsxZj.jpg",
"https://i.imgur.com/g3sZjdQ.jpg",
"https://i.imgur.com/AYzq2NV.jpg",
"https://i.imgur.com/mLrebXj.jpg",
"https://i.imgur.com/JTZtk55.jpg",
"https://i.imgur.com/oAsiAAl.jpg",
"https://i.imgur.com/HcwP0ES.jpg",
"https://i.imgur.com/tk2tmFS.jpg",
"https://i.imgur.com/hRsp56d.jpg",
"https://i.imgur.com/D8Iyhix.jpg",
"https://i.imgur.com/UZpU9BJ.jpg",
"https://i.imgur.com/C4S2okK.jpg",
"https://i.imgur.com/2qw7VJC.jpg",
"https://i.imgur.com/R4dRNqd.jpg",
"https://i.imgur.com/Ikv0ga9.jpg",
"https://i.imgur.com/8duWQed.jpg",
"https://i.imgur.com/fQnZ3nn.jpg",
"https://i.imgur.com/z6vLJXy.jpg",
"https://i.imgur.com/TspvH5t.jpg",
"https://i.imgur.com/Sx4USrj.jpg",
"https://i.imgur.com/5lQc292.jpg",
"https://i.imgur.com/lirKmec.jpg",
"https://i.imgur.com/pUOwIfM.jpg",
"https://i.imgur.com/8u2r0Ja.jpg",
"https://i.imgur.com/PvsJNXv.jpg",
"https://i.imgur.com/4ZY0Bl4.jpg",
"https://i.imgur.com/N0vLuOg.jpg",
"https://i.imgur.com/a3F6fCV.jpg",
"https://i.imgur.com/Nh4V4nn.jpg",
"https://i.imgur.com/XB42aDR.jpg",
"https://i.imgur.com/1CmokyW.jpg",
"https://i.imgur.com/Y6GdoHm.jpg",
"https://i.imgur.com/lCV28X6.jpg",
"https://i.imgur.com/mFlPDGt.jpg",
"https://i.imgur.com/w8AIT1t.jpg",
"https://i.imgur.com/fb4fUtt.png",
"https://i.imgur.com/KKyaHfJ.jpg",
"https://i.imgur.com/dbFoSbA.jpg",
"https://i.imgur.com/DMr2IKw.jpg",
"https://i.imgur.com/iT7TSp9.jpg",
"https://i.imgur.com/bLBxGho.jpg",
"https://i.imgur.com/Br6q8pC.jpg",
"https://i.imgur.com/muBR6lw.jpg",
"https://i.imgur.com/vgm9zBS.png",
"https://i.imgur.com/zXYFmK4.jpg",
"https://i.imgur.com/3KM71VA.jpg",
"https://i.imgur.com/CpDNV6A.jpg",
"https://i.imgur.com/rYOw69U.jpg",
"https://i.imgur.com/cRkVY8g.jpg",
"https://i.imgur.com/9hGlTDQ.jpg",
"https://i.imgur.com/mlgcVQ3.jpg",
"https://i.imgur.com/oj4Rctj.jpg",
"https://i.imgur.com/NYfbMfG.jpg",
"https://i.imgur.com/BFzToRW.jpg",
  ];
	 var callback = () => api.sendMessage({body:`[ Source By BuiChiThong ]`,attachment: fs.createReadStream(__dirname + "/cache/5.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/5.jpg"));	
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/5.jpg")).on("close",() => callback());
   };